### PR TITLE
Merge develop into master branch.

### PR DESCRIPTION
**Pull request by emiryazicii**
Last README.md file updates.

### CODE REVIEW

**Review by jika17 — APPROVED** [review]
Perfect!

**Comment by emiryazicii** [comment]
> Perfect!

Thank you Jika :) You are the fastest teammate ...

**Review by bataborisa — APPROVED** [review]
Everything looks nice! 

Go Group_26!!!

**Comment by emiryazicii** [comment]
> Everything looks nice!
> 
> Go Group_26!!!

Thank you Boris, your feedback are so important to improve our project. Keep being so active :)

**Review by Fleshka87 — COMMENTED** [review]
thank you!

**Comment by emiryazicii** [comment]
> thank you!

It's my pleasure ! :)

**Pull request merged**
