### PR TITLE
task 1&3 

### PR DESCRIPTION
**Pull request by Guendouz27**

### CODE REVIEW

**Review by emiryazicii — COMMENTED** [review]
Hey Mohammed , just a friendly reminder ; we supposed to share our solutions tomorrow at the meeting.

**Review by emiryazicii — CHANGES_REQUESTED** [review]
And also you need to  send the pull request to develop branch. We will discuss before approve and merge each team member's requests. Thanks.

**Comment by Guendouz27** [comment]
oh ok sorry am still confused lol

**Comment by emiryazicii** [comment]
> oh ok sorry am still confused lol

No problem brother, it's all good. After doing more practice, everything will be clearer. Don't worry.

**Review by emiryazicii — APPROVED** [review]
Thanks for updating your request, It looks perfect now.

**Pull request merged**
