### PR TITLE
Add my solutions for week04 tasks.

### PR DESCRIPTION
**Pull request by emiryazicii**
Also Add comments to explain all the steps to solve the tasks. Add javaDoc to display what method has which function.

### CODE REVIEW

**Review by jika17 — COMMENTED** [review]
It's perfect! Good job!

**Review by jika17 — APPROVED** [review]
Nice!

**Comment by jika17** [comment]
Approved!

**Comment by emiryazicii** [comment]
> It's perfect! Good job!

Thanks a lot Jika :)

**Pull request merged**
